apiVersion: sources.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: speech-to-text
  labels:
    app.kubernetes.io/part-of: hey-rodney
spec:
  consumerGroup: hey-rodney
  bootstrapServers:
    - kafka-eventing-kafka-bootstrap.knative-eventing.svc:9092
  topics:
    - knative-messaging-kafka.drogue-iot.iot-channel
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: watson-stt-converter
